name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Using Python 3.10 for better compatibility

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install --force-reinstall pytest
          pip install -r requirements.txt

      - name: Check Installed Packages
        run: |
          source venv/bin/activate
          pip list | grep pytest || echo "pytest NOT installed"

      - name: Debug Python Path
        run: |
          which python
          source venv/bin/activate
          which pytest
          python -m pytest --version || echo "pytest command failed"

      - name: Run Tests
        run: |
          source venv/bin/activate
          python -m pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          echo "Deploying the application..."
          # Add your deployment commands here
