name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # ✅ Ensure pytest is included

      - name: Verify pytest Installation
        run: |
          python --version
          which python
          which pytest || echo "pytest NOT found"
          python -m pytest --version || echo "pytest not working"

      - name: Run Tests
        run: python -m pytest  # ✅ Run pytest using Python module

  deploy:
    needs: build
    runs-on: ubuntu-22.04


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          echo "Deploying the application..."
          # Add deployment commands here
